### ISSUE TITLE
how to have serverless and edge coexist?

### ISSUE THREAD

**Issue by HananoshikaYomaru** [hi-ogawa/remix-vite-deployment-examples#12]
I have a project with remix on vercel serverless function following the demo. Now I want to add pages that run on edge but I found that their build script is different. is it possible to have them coexist, for example vercel they allow the page to expose 

```ts
export const config = { runtime: "edge" }
```

to mark a page as edge. is it possible? how can we modify the build script to make it work?

**Comment by hi-ogawa** [comment]
Thanks for trying out the demo.

My examples here are for testing ideas while Remix Vite was in experimental phase. Now that Vercel officially supports Remix Vite deployment https://github.com/vercel/vercel/pull/11031, so probably it's better for you to switch to that.

My deployment here doesn't consider splitting server code to multiple runtime and probably it wouldn't be so easy to modify the script.

**Comment by HananoshikaYomaru** [comment]
Alright thx for answering.
